### ISSUE TITLE
httpserver可以正常访问,然后想在httpserver api请求里面访问其tarsserver服务。发现出错。求助。。

### ISSUE THREAD

**Issue by skylway** [TarsCloud/TarsGo#159]
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xc000012c00, 0x15, 0xc00000e0f8)
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0xa7
github.com/TarsCloud/TarsGo/tars.checkPanic()
	/www/go/src/github.com/TarsCloud/TarsGo/tars/panic.go:16 +0x16b
panic(0x6ad800, 0xc000047760)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
time.NewTicker(0x0, 0x0)
	/usr/lib/golang/src/time/tick.go:23 +0x18f
github.com/TarsCloud/TarsGo/tars/util/rtimer.NewTimeWheel(0x0, 0x15, 0x0)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/util/rtimer/timewheel.go:56 +0x124
github.com/TarsCloud/TarsGo/tars/util/rtimer.After(0x0, 0x0)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/util/rtimer/timewheel.go:25 +0xe1
github.com/TarsCloud/TarsGo/tars.(*ObjectProxy).Invoke(0xc00000cd80, 0x75cb80, 0xc0000140a0, 0xc0000aa460, 0x0, 0x0, 0x0)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/object.go:53 +0x1b8
github.com/TarsCloud/TarsGo/tars.(*ServantProxy).Tars_invoke(0xc000069b60, 0x75cb80, 0xc0000140a0, 0xc00012e000, 0x713b17, 0x19, 0xc00011a330, 0x1d, 0x40, 0x0, ...)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/servant.go:71 +0x5b6
github.com/TarsCloud/TarsGo/tars/protocol/res/queryf.(*QueryF).FindObjectByIdInSameGroup(0xc000047420, 0x714518, 0x1b, 0xc000137298, 0xc000137280, 0x0, 0x0, 0x0, 0xc000000000, 0x1, ...)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/protocol/res/queryf/QueryF_IF.go:565 +0x1ad
github.com/TarsCloud/TarsGo/tars.(*EndpointManager).findAndSetObj(0xc00005c6c0, 0xc000047420)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/endpointmanager.go:198 +0xbf3
github.com/TarsCloud/TarsGo/tars.(*EndpointManager).setObjName(0xc00005c6c0, 0x714518, 0x1b)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/endpointmanager.go:52 +0x3e3
github.com/TarsCloud/TarsGo/tars.(*EndpointManager).Init(0xc00005c6c0, 0x714518, 0x1b, 0xc0000512c0, 0x1, 0xc00000cd60)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/endpointmanager.go:74 +0xee
github.com/TarsCloud/TarsGo/tars.(*ObjectProxy).Init(0xc00000cd60, 0xc0000512c0, 0x714518, 0x1b)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/object.go:27 +0x86
github.com/TarsCloud/TarsGo/tars.(*ObjectProxyFactory).GetObjectProxy(0xc000137d98, 0x714518, 0x1b, 0x0)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/object.go:88 +0xf6
github.com/TarsCloud/TarsGo/tars.(*ServantProxy).Init(0xc000069aa0, 0xc0000512c0, 0x714518, 0x1b)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/servant.go:36 +0x11b
github.com/TarsCloud/TarsGo/tars.(*ServantProxyFactory).GetServantProxy(0xc00000cd40, 0x714518, 0x1b, 0x7)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/servant.go:114 +0xd1
github.com/TarsCloud/TarsGo/tars.(*Communicator).StringToProxy(0xc0000512c0, 0x714518, 0x1b, 0x7597c0, 0xc000047210)
	/www/go/src/github.com/TarsCloud/TarsGo/tars/communicator.go:82 +0x42
main.call()
	/www/go/src/TestApp/WupProxy/WupProxy.go:25 +0xd3
main.init.0()
	/www/go/src/TestApp/WupProxy/WupProxy.go:11 +0x26

**Comment by skylway** [comment]
是调用姿势不对
本地运行程序需要自己在配置文件里面加上client配置参数
